title: Flashing light warning
hero_image: images/banner.png
description: Flashing light warning
version: 4
listed: false
copyedit: false
last_tested: "2022-02-28"
steps:
  - title: Flashing light warning
