---
title: Avertissement lumière clignotante
hero_image: images/banner.png
description: Avertissement lumière clignotante
version: 4
listed: false
copyedit: false
last_tested: "2022-02-28"
steps:
  - title: Avertissement lumière clignotante
